<?php
$c_cust_sql = "SELECT COUNT(*) FROM " . $table_customer ;
$c_cust = $mysqli->query($c_cust_sql);
$cd_cust = $c_cust->fetch_assoc(); 
$c_cust_parents_sql = "SELECT COUNT(*) FROM " . $table_customer . " where is_parent = 1";
$c_cust_parents = $mysqli->query($c_cust_parents_sql);
$cd_cust_parents = $c_cust_parents->fetch_assoc(); 
$c_cust_student_adult_sql = "SELECT COUNT(*) FROM " . $table_customer . " where is_student_adult = 1";
$c_cust_student_adult = $mysqli->query($c_cust_student_adult_sql);
$cd_cust_student_adult = $c_cust_student_adult->fetch_assoc(); 
$c_cust_student_minor_sql = "SELECT COUNT(*) FROM " . $table_customer . " where is_student_minor = 1";
$c_cust_student_minor = $mysqli->query($c_cust_student_minor_sql);
$cd_cust_student_minor = $c_cust_student_minor->fetch_assoc(); 
$c_cust_student_minor_sql = "SELECT COUNT(*) FROM " . $table_customer . " where is_student_minor = 1";
$c_cust_student_minor = $mysqli->query($c_cust_student_minor_sql);
$cd_cust_student_minor = $c_cust_student_minor->fetch_assoc();
$c_cust_relative_sql = "SELECT COUNT(*) FROM " . $table_customer . " where is_relative = 1";
$c_cust_relative = $mysqli->query($c_cust_relative_sql);
$cd_cust_relative = $c_cust_relative->fetch_assoc();  
$c_cust_sibling_sql = "SELECT COUNT(*) FROM " . $table_customer . " where is_sibling = 1";
$c_cust_sibling = $mysqli->query($c_cust_sibling_sql);
$cd_cust_sibling = $c_cust_sibling->fetch_assoc();
$c_cust_instructor_sql = "SELECT COUNT(*) FROM " . $table_customer . " where is_instructor = 1";
$c_cust_instructor = $mysqli->query($c_cust_instructor_sql);
$cd_cust_instructor = $c_cust_instructor->fetch_assoc();
$c_cust_vol_adult_sql = "SELECT COUNT(*) FROM " . $table_customer . " where is_vol_adult = 1";
$c_cust_vol_adult = $mysqli->query($c_cust_vol_adult_sql);
$cd_cust_vol_adult = $c_cust_vol_adult->fetch_assoc();
$c_cust_vol_minor_sql = "SELECT COUNT(*) FROM " . $table_customer . " where is_vol_minor = 1";
 // echo $c_cust_vol_minor_sql; exit;
$c_cust_vol_minor = $mysqli->query($c_cust_vol_minor_sql);
$cd_cust_vol_minor = $c_cust_vol_minor->fetch_assoc();
$c_cust_sponsor_sql = "SELECT COUNT(*) FROM " . $table_customer . " where is_sponsor = 1";
$c_cust_sponsor = $mysqli->query($c_cust_sponsor_sql);
$cd_cust_sponsor = $c_cust_sponsor->fetch_assoc();
$c_cust_alumni_sql = "SELECT COUNT(*) FROM " . $table_customer . " where is_alumni = 1";
$c_cust_alumni = $mysqli->query($c_cust_alumni_sql);
$cd_cust_alumni = $c_cust_alumni->fetch_assoc();
$c_cust_electronic_sql = "SELECT COUNT(*) FROM " . $table_customer . " where h_env_electronic = 1";
$c_cust_electronic = $mysqli->query($c_cust_electronic_sql);
$cd_cust_electronic = $c_cust_electronic->fetch_assoc();
$c_cust_compsci_sql = "SELECT COUNT(*) FROM " . $table_customer . " where h_env_compsci = 1";
$c_cust_compsci = $mysqli->query($c_cust_compsci_sql);
$cd_cust_compsci = $c_cust_compsci->fetch_assoc();
$c_cust_mecheng_sql = "SELECT COUNT(*) FROM " . $table_customer . " where h_env_mecheng = 1";
$c_cust_mecheng = $mysqli->query($c_cust_mecheng_sql);
$cd_cust_mecheng = $c_cust_mecheng->fetch_assoc();
$c_cust_verified_sql = "SELECT COUNT(*) FROM " . $table_customer . " where Verified = 1";
$c_cust_verified = $mysqli->query($c_cust_verified_sql);
$cd_cust_verified = $c_cust_verified->fetch_assoc();
?>