<?php
$c_stud_sql = "SELECT COUNT(*) FROM " . $table_student;
$c_stud = $mysqli->query($c_stud_sql);
$cd_stud = $c_stud->fetch_assoc(); 
$c_stud_verified_sql = "SELECT COUNT(*) FROM " . $table_student . " where Verified = 1";
$c_stud_verified = $mysqli->query($c_stud_verified_sql);
$cd_stud_verified = $c_stud_verified->fetch_assoc();
$c_stud_parents_sql = "SELECT COUNT(*) FROM " . $table_student . " where is_parent = 1";
$c_stud_parents = $mysqli->query($c_stud_parents_sql);
$cd_stud_parents = $c_stud_parents->fetch_assoc(); 
$c_stud_student_adult_sql = "SELECT COUNT(*) FROM " . $table_student . " where is_student_adult = 1";
$c_stud_student_adult = $mysqli->query($c_stud_student_adult_sql);
$cd_stud_student_adult = $c_stud_student_adult->fetch_assoc(); 
$c_stud_student_minor_sql = "SELECT COUNT(*) FROM " . $table_student . " where is_student_minor = 1";
$c_stud_student_minor = $mysqli->query($c_stud_student_minor_sql);
$cd_stud_student_minor = $c_stud_student_minor->fetch_assoc(); 
$c_stud_student_minor_sql = "SELECT COUNT(*) FROM " . $table_student . " where is_student_minor = 1";
$c_stud_student_minor = $mysqli->query($c_stud_student_minor_sql);
$cd_stud_student_minor = $c_stud_student_minor->fetch_assoc();
$c_stud_relative_sql = "SELECT COUNT(*) FROM " . $table_student . " where is_relative = 1";
$c_stud_relative = $mysqli->query($c_stud_relative_sql);
$cd_stud_relative = $c_stud_relative->fetch_assoc();  
$c_stud_sibling_sql = "SELECT COUNT(*) FROM " . $table_student . " where is_sibling = 1";
$c_stud_sibling = $mysqli->query($c_stud_sibling_sql);
$cd_stud_sibling = $c_stud_sibling->fetch_assoc();
$c_stud_instructor_sql = "SELECT COUNT(*) FROM " . $table_student . " where is_instructor = 1";
$c_stud_instructor = $mysqli->query($c_stud_instructor_sql);
$cd_stud_instructor = $c_stud_instructor->fetch_assoc();
$c_stud_vol_adult_sql = "SELECT COUNT(*) FROM " . $table_student . " where is_vol_adult = 1";
$c_stud_vol_adult = $mysqli->query($c_stud_vol_adult_sql);
$cd_stud_vol_adult = $c_stud_vol_adult->fetch_assoc();
$c_stud_vol_minor_sql = "SELECT COUNT(*) FROM " . $table_student . " where is_vol_minor = 1";
 // echo $c_stud_vol_minor_sql; exit;
$c_stud_vol_minor = $mysqli->query($c_stud_vol_minor_sql);
$cd_stud_vol_minor = $c_stud_vol_minor->fetch_assoc();
$c_stud_sponsor_sql = "SELECT COUNT(*) FROM " . $table_student . " where is_sponsor = 1";
$c_stud_sponsor = $mysqli->query($c_stud_sponsor_sql);
$cd_stud_sponsor = $c_stud_sponsor->fetch_assoc();
$c_stud_alumni_sql = "SELECT COUNT(*) FROM " . $table_student . " where is_alumni = 1";
$c_stud_alumni = $mysqli->query($c_stud_alumni_sql);
$cd_stud_alumni = $c_stud_alumni->fetch_assoc();
?>