<?php
$class_cols = array(
	0 => array('class_cols' => 'ID'),
	1 => array('class_cols' => 'Class ID'),
	2 => array('class_cols' => 'Class Name'),
	3 => array('class_cols' => 'Department'),
	4 => array('class_cols' => 'Class Number'),
	5 => array('class_cols' => 'Class Section'),
	6 => array('class_cols' => 'Is Class Active'),
	7 => array('class_cols' => 'Instructor'),
	8 => array('class_cols' => 'Internal Notes'),
	9 => array('class_cols' => 'Class Description'),
	10 => array('class_cols' => 'Additional Info'),
	11 => array('class_cols' => 'Prerequisite'),
	12 => array('class_cols' => 'Start Week'),
	13 => array('class_cols' => 'End Week'),
	14 => array('class_cols' => 'Minimum Age'),
	15 => array('class_cols' => 'Maximum Age'),
	16 => array('class_cols' => 'Consumables Fee'),
	17 => array('class_cols' => 'Hourly Fee'),
	18 => array('class_cols' => 'Registration Fee'),
	19 => array('class_cols' => 'Price Included For Interns'),
	20 => array('class_cols' => 'Class For Interns Only'),
	21 => array('class_cols' => 'Has Field Trips'),
	22 => array('class_cols' => 'Field Trip Wish List'),
	23 => array('class_cols' => 'Class'),
	24 => array('class_cols' => 'Workshop'),
	25 => array('class_cols' => 'Group-based'),
	26 => array('class_cols' => 'Seasonal Classification'),
	27 => array('class_cols' => 'Number of Weeks'),
	28 => array('class_cols' => 'Monday'),
	29 => array('class_cols' => 'Tuesday'),
	30 => array('class_cols' => 'Wednesday'),
	31 => array('class_cols' => 'Thursday'),
	32 => array('class_cols' => 'Friday'),
	33 => array('class_cols' => 'Saturday'),
	34 => array('class_cols' => 'Sunday'),
	35 => array('class_cols' => 'Hours Per Class'),
	36 => array('class_cols' => 'Meetings Per Week'),
	37 => array('class_cols' => 'Total Meetings'),
	38 => array('class_cols' => 'Total Class Time Hours'),
	39 => array('class_cols' => 'Start Time'),
	40 => array('class_cols' => 'End Time'),
	41 => array('class_cols' => 'AREA'),
	42 => array('class_cols' => 'Image 1'),
	43 => array('class_cols' => 'Image 2'),
	44 => array('class_cols' => 'Image 3'),
	45 => array('class_cols' => 'External Link 1'),
	46 => array('class_cols' => 'External Link 2'),
	47 => array('class_cols' => 'External Link 3'),
	48 => array('class_cols' => 'UND_1'),
	49 => array('class_cols' => 'UND_2'),
	50 => array('class_cols' => 'UND_3'),
	51 => array('class_cols' => 'UND_4'),
	52 => array('class_cols' => 'UND_5'),
	53 => array('class_cols' => 'UND_6'),
	54 => array('class_cols' => 'UND_7'),
	55 => array('class_cols' => 'UND_8'),
	56 => array('class_cols' => 'UND_9'),
	57 => array('class_cols' => 'UND_10'),
	58 => array('class_cols' => 'Class Created'),
	59 => array('class_cols' => 'Publish Date'),
	60 => array('class_cols' => 'Enrollment Limit'),
	61 => array('class_cols' => 'Not Included For Interns'),
	62 => array('class_cols' => 'Seminars'),
	63 => array('class_cols' => 'Events'),
	64 => array('class_cols' => 'Price For Interns'),
	65 => array('class_cols' => 'Price For Students'),
	66 => array('class_cols' => 'Accreditation Status'),
	67 => array('class_cols' => 'Accreditation Org Name'),
	68 => array('class_cols' => 'Number of Units'),
	69 => array('class_cols' => 'Grade Level'),
);
$student_cols = array(
	0 => array('student_cols' => 'ID'),
	1 => array('student_cols' => 'Date Added'),
	2 => array('student_cols' => 'First Name'),
	3 => array('student_cols' => 'Last Name'),
	4 => array('student_cols' => 'Date Of Birth'),
	5 => array('student_cols' => 'Grade Level'),
	6 => array('student_cols' => 'Grade Level Date'),
	7 => array('student_cols' => 'School'),
	8 => array('student_cols' => 'Gender'),
	9 => array('student_cols' => 'Cell Phone'),
	10 => array('student_cols' => 'Email'),
	11 => array('student_cols' => 'Is A Parent'),
	12 => array('student_cols' => 'Is A Student Adult'),
	13 => array('student_cols' => 'Is A Student Minor'),
	14 => array('student_cols' => 'Is Relative'),
	15 => array('student_cols' => 'Is Sibling'),
	16 => array('student_cols' => 'Is An Instructor'),
	17 => array('student_cols' => 'Is An Adult Volunteer'),
	18 => array('student_cols' => 'Is A Volunteering Minor'),
	19 => array('student_cols' => 'Is A Sponsor'),
	20 => array('student_cols' => 'Is An Alumni'),
	21 => array('student_cols' => 'Linked Customer ID'),
	22 => array('student_cols' => 'Medical Condition'),
	23 => array('student_cols' => 'Medical Condition Desc'),
	24 => array('student_cols' => 'Is Medical Condition Life Threatening'),
	25 => array('student_cols' => 'Goals'),
	26 => array('student_cols' => 'Emergency Contact First Name'),
	27 => array('student_cols' => 'Emergency Contact Last Name'),
	28 => array('student_cols' => 'Emergency Contact Phone Number'),
	29 => array('student_cols' => 'Emergency Contact Email'),
	30 => array('student_cols' => 'Address Line 1'),
	31 => array('student_cols' => 'Address Line 2'),
	32 => array('student_cols' => 'Class ID'),
	33 => array('student_cols' => 'Is Student Activated?'),
	34 => array('student_cols' => 'Password'),
	35 => array('student_cols' => 'Is An Intern'),
	36 => array('student_cols' => 'Start Date of Internship'),
	37 => array('student_cols' => 'End Date of Internship'),
);

$customer_cols = array(
	0 => array('customer_cols' => 'ID'),
	1 => array('customer_cols' => 'Date Created'),
	2 => array('customer_cols' => 'First Name'),
	3 => array('customer_cols' => 'Last Name'),
	4 => array('customer_cols' => 'Customer UUID'),
	5 => array('customer_cols' => 'Is Parent'),
	6 => array('customer_cols' => 'Is Student Adult'),
	7 => array('customer_cols' => 'Is Student Minor'),
	8 => array('customer_cols' => 'Is Relative'),
	9 => array('customer_cols' => 'Is Sibling'),
	10 => array('customer_cols' => 'Is Instructor'),
	11 => array('customer_cols' => 'Is Volunteer Adult'),
	12 => array('customer_cols' => 'Is Volunteer Minor'),
	13 => array('customer_cols' => 'Is Sponsor'),
	14 => array('customer_cols' => 'Is Alumni'),
	15 => array('customer_cols' => 'Password'),
	16 => array('customer_cols' => 'Home Environment Electronic'),
	17 => array('customer_cols' => 'Home Environment Comp Sci'),
	18 => array('customer_cols' => 'Home Environment Mech Eng'),
	19 => array('customer_cols' => 'Referred By'),
	20 => array('customer_cols' => 'Referred By Other'),
	21 => array('customer_cols' => 'Address Line 1'),
	22 => array('customer_cols' => 'Address Line 2'),
	23 => array('customer_cols' => 'Email'),
	24 => array('customer_cols' => 'Verified'),
	25 => array('customer_cols' => 'City'),
	26 => array('customer_cols' => 'State'),
	27 => array('customer_cols' => 'Zipcode'),
	28 => array('customer_cols' => 'Country'),
	29 => array('customer_cols' => 'Phone 1'),
	30 => array('customer_cols' => 'Phone 2'),
	31 => array('customer_cols' => 'Customer ID'),
	32 => array('customer_cols' => 'Employer\'s Name'),
	33 => array('customer_cols' => 'Position Title'),
	34 => array('customer_cols' => 'Department'),
	35 => array('customer_cols' => 'Area of Expertise'),
	36 => array('customer_cols' => 'Work Address'),
	37 => array('customer_cols' => 'Work City'),
	38 => array('customer_cols' => 'Work State'),
	39 => array('customer_cols' => 'Work Zipcode'),
	40 => array('customer_cols' => 'Work Phone'),
	41 => array('customer_cols' => 'Work Email'),
	42 => array('customer_cols' => 'Work Notes'),
	43 => array('customer_cols' => 'Customer Willing to Volunteer'),
);

$transaction_cols = array(
	0 => array('transaction_cols' => 'Student First Name'),
	1 => array('transaction_cols' => 'Student Last Name'),
	2 => array('transaction_cols' => 'Class Name'),
	3 => array('transaction_cols' => 'Time Signed Up'),
	4 => array('transaction_cols' => 'Amount Due'),
	5 => array('transaction_cols' => 'Amount Paid'),
	6 => array('transaction_cols' => 'Paid In Full'),
);
?>